package com.abadeksvp.csvtool.integration;


import java.time.LocalDate;
import java.util.List;

import com.abadeksvp.csvtool.model.entity.Note;

import lombok.experimental.UtilityClass;

@UtilityClass
public class TestDataBuilder {

    public static List<Note> buildExpectedCreatedNotes() {
        return List.of(
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB001")
                        .code("271636001")
                        .displayValue("Polsslag regelmatig")
                        .longDescription("The long description is necessary")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(1L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB001")
                        .code("61086009")
                        .displayValue("Polsslag onregelmatig")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(2L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB001")
                        .code("Type 1")
                        .displayValue("Losse harde keutels, zoals noten")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 2")
                        .displayValue("Als een worst, maar klonterig")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 3")
                        .displayValue("Als een worst, maar met barstjes aan de buitenkant")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 4")
                        .displayValue("Als een worst of slang, glad en zacht")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 5")
                        .displayValue("Zachte keutels met duidelijke randen")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 6")
                        .displayValue("Zachte stukjes met gehavende randen")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB002")
                        .code("Type 7")
                        .displayValue("Helemaal vloeibaar")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("307047009")
                        .displayValue("Rectale temperatuur")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(1L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("415945006")
                        .displayValue("Orale temperatuur (onder de tong)")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(2L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("415882003")
                        .displayValue("Axillaire temperatuur (onder de oksel)")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("415929009")
                        .displayValue("Inguinale temperatuur (via de lies)")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("415974002")
                        .displayValue("Tympanische temperatuur")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(3L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("415922000")
                        .displayValue("Temporale temperatuur")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("364246006")
                        .displayValue("Vaginale temperatuur")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("698832009")
                        .displayValue("Blaastemperatuur")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB003")
                        .code("276885007")
                        .displayValue("Kern temperatuur (invasief gemeten)")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build()
        );
    }

    public static List<Note> buildExpectedUpdatedNotes() {
        return List.of(
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB001")
                        .code("271636001")
                        .displayValue("Polsslag regelmatig updated")
                        .longDescription("The long description is necessary")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(1L)
                        .build(),
                Note.builder()
                        .source("ZIB")
                        .codeListCode("ZIB005")
                        .code("6108600654")
                        .displayValue("New note")
                        .longDescription("")
                        .fromDate(LocalDate.of(2019, 1, 1))
                        .toDate(null)
                        .sortingPriority(null)
                        .build()
        );
    }
}
